using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using static School.Domain.BaseEntity;
using School.Domain.School;

namespace School.Domain.Transport
{
    public class Vehicle : AuditEntity<int>, ITenantEntity
    {
        [Key] 
        public int Id { get; set; }

        [Required, MaxLength(100)] 
        public string Name { get; set; } = null!; // Vehicle Custom Name / Code (e.g. Bus-01)

        [Required, MaxLength(30)] 
        public string RegistrationNumber { get; set; } = null!; // Plate Number (e.g. MH12AB1234)

        [Required, MaxLength(30)] 
        public string VehicleType { get; set; } = "Bus"; // Bus, Mini Bus, Van, Car, Electric Bus

        public int Capacity { get; set; } // Max seat capacity
        
        [MaxLength(100)] 
        public string? GpsDeviceNumber { get; set; } // Associated GPS Device Hardware ID
        
        [MaxLength(100)] 
        public string? RfidReaderId { get; set; } // Associated RFID Reader Hardware ID

        [MaxLength(100)] 
        public string? Model { get; set; }
        
        [MaxLength(100)] 
        public string? Manufacturer { get; set; }
        
        public int Year { get; set; }

        [MaxLength(100)] 
        public string? EngineNumber { get; set; }

        [MaxLength(100)] 
        public string? ChassisNumber { get; set; }

        [MaxLength(100)] 
        public string? InsuranceNumber { get; set; }
        
        public DateTime? InsuranceExpiry { get; set; }

        [MaxLength(100)] 
        public string? FitnessCertificate { get; set; }
        
        public DateTime? FitnessExpiry { get; set; }

        [MaxLength(100)] 
        public string? PermitNumber { get; set; }
        
        public DateTime? PermitExpiry { get; set; }

        [MaxLength(100)] 
        public string? PucCertificate { get; set; }
        
        public DateTime? PucExpiry { get; set; }

        [MaxLength(500)] 
        public string? RcUploadUrl { get; set; }

        [MaxLength(500)] 
        public string? InsuranceUploadUrl { get; set; }

        [MaxLength(500)] 
        public string? PhotoUrl { get; set; }

        [MaxLength(500)] 
        public string? DocumentsUrl { get; set; }

        [MaxLength(30)] 
        public string FuelType { get; set; } = "Diesel"; // Diesel, Petrol, CNG, Electric

        public double Mileage { get; set; } // Expected Average
        
        public double FuelTankCapacity { get; set; }
        
        public double CurrentOdometer { get; set; }

        [Required, MaxLength(30)] 
        public string Status { get; set; } = "Active"; // Active, Maintenance, Inactive

        [MaxLength(500)] 
        public string? Remarks { get; set; }

        [MaxLength(200)] 
        public string? QrCode { get; set; } // Autogenerated QR String

        [MaxLength(200)] 
        public string? Barcode { get; set; }

        // Backwards compatibility fields for old database migrations
        [MaxLength(50)]
        public string? DriverName { get; set; }
        [MaxLength(20)]
        public string? DriverPhone { get; set; }

        public int SchoolRegistrationId { get; set; }
        [ForeignKey(nameof(SchoolRegistrationId))] 
        public virtual SchoolRegistration SchoolRegistration { get; set; } = null!;
    }
}
