using Microsoft.Extensions.Logging;
using School.Services.Interfaces;
using School_DTOs.Reporting;

namespace School.Services.Reporting
{
    /// <summary>
    /// Queues and sends generated report files as email attachments.
    /// Uses the existing IEmailService for actual delivery with retry support.
    /// </summary>
    public class ReportEmailService : IReportEmailService
    {
        private readonly IReportingEngineService _engineService;
        private readonly IEmailService _emailService;
        private readonly ILogger<ReportEmailService> _logger;

        public ReportEmailService(
            IReportingEngineService engineService,
            IEmailService emailService,
            ILogger<ReportEmailService> logger)
        {
            _engineService = engineService;
            _emailService = emailService;
            _logger = logger;
        }

        public async Task<bool> EmailReportAsync(
            ReportEmailRequest request,
            string triggeredBy,
            int? tenantId = null)
        {
            try
            {
                // 1. Generate the report bytes
                var execRequest = new ReportExecutionRequest
                {
                    ReportCode = request.ReportCode,
                    ReportTemplateId = request.ReportTemplateId,
                    Format = request.Format,
                    Parameters = request.Parameters,
                    TenantId = tenantId
                };

                var fileBytes = await _engineService.GenerateAsync(execRequest, triggeredBy, tenantId);

                // 2. Build file name and content type
                var ext = request.Format.ToUpperInvariant() switch
                {
                    "EXCEL" => ".xlsx",
                    "WORD" => ".docx",
                    "CSV" => ".csv",
                    "XML" => ".xml",
                    "JSON" => ".json",
                    _ => ".pdf"
                };

                var reportName = request.ReportCode.Replace("_", " ");
                var fileName = $"{reportName}_{DateTime.Now:yyyyMMdd_HHmm}{ext}";

                var subject = request.Subject
                    ?? $"{reportName} — {DateTime.Now:dd-MMM-yyyy}";

                var body = request.Body
                    ?? $"<p>Please find the attached <strong>{reportName}</strong> report.</p>"
                     + $"<p>Generated on: {DateTime.Now:dd-MMM-yyyy HH:mm}<br/>Generated by: {triggeredBy}</p>"
                     + "<p><em>This is an automated email from SchoolSaaS ERP.</em></p>";

                // 3. Queue via existing email service (which handles SMTP + retry)
                foreach (var to in request.ToEmails)
                {
                    _emailService.QueueTemplateEmail(
                        to,
                        "ReportEmail",
                        new Dictionary<string, string>
                        {
                            ["Subject"] = subject,
                            ["Body"] = body,
                            ["ReportName"] = reportName
                        },
                        fileBytes,
                        fileName);
                }

                _logger.LogInformation(
                    "Report [{Code}] emailed to {Count} recipients by {User}",
                    request.ReportCode, request.ToEmails.Count, triggeredBy);

                return true;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to email report [{Code}]", request.ReportCode);
                return false;
            }
        }
    }
}
